NavigationRail
ldbv-by/bav4 pull request #2083
Opened 2023-11-28 14:46 UTC by alsturm

2024-02-01 06:43 UTC, thiloSchlemmer commented on src/modules/chips/components/chipsContainer/ChipsContainer.js
> +			<div id="chipscontainer" class="${getOrientationClass()} ${getMinWidthClass()} ${getOverlayClass()} ${getOverlayNavClass()} chips__container">
I suggest to collect all classes in a classMap, to have the controlflow in one place like:
```suggestion
    const classes = {
            'is-open-navigationRail':isOpenNavigationRail && !isPortrait,
            'is-desktop': hasMinWidth,
            'is-tablet':!hasMinWidth,
            'is-portrait' : isPortrait,
            'is-landscape':!isPortrait
```
}`

2024-02-01 06:49 UTC, thiloSchlemmer commented on src/modules/footer/components/Footer.js
>  				<div class="${getOrientationClass()} ${getMinWidthClass()} ${isEmbedded()}">
same suggest as in ChipsContainer.js --> use of ${classMap(classes)}

2024-02-01 06:50 UTC, thiloSchlemmer commented on src/modules/header/components/Header.js
> +				<div class="${getOrientationClass()} ${getMinWidthClass()} ${getDemoClass()} ${getOverlayTestClass()}">
same suggest as in ChipsContainer.js --> use of ${classMap(classes)}

2024-02-01 06:52 UTC, thiloSchlemmer commented on src/modules/menu/components/mainMenu/MainMenu.js
> +				<div id="mainmenu" class="main-menu ${getOverlayClass()} ${getOverlayNavClass()} ${getMinWidthClass()} ${getFullSizeClass()}">
same suggest as in ChipsContainer.js --> use of ${classMap(classes)}

2024-02-01 06:54 UTC, thiloSchlemmer commented on src/modules/menu/components/navigationRail/NavigationRail.js
> +			<div class="navigation-rail__container ${getOverlayClass()} ${getOrientationClass()}">
same suggest as in ChipsContainer.js --> use of ${classMap(classes)}

2024-02-01 06:58 UTC, thiloSchlemmer commented on src/modules/stackables/components/bottomSheet/BottomSheet.js
>  			<ba-icon id="close-icon" class='tool-container__close-button' .icon='${closeIcon}' .size=${1.6} .color=${'var(--text2)'} .color_hover=${'var(--text2)'} @click=${onDismiss}>
Unclosed tag

2024-02-01 06:58 UTC, thiloSchlemmer commented on src/modules/stackables/components/bottomSheet/BottomSheet.js
> +		<div class='bottom-sheet ${getOverlayClass()} ${getOverlayNavClass()} ${getOrientationClass()}' data-test-id>
same suggest as in ChipsContainer.js --> use of ${classMap(classes)}

2024-02-01 07:23 UTC, thiloSchlemmer commented on src/plugins/NavigationRailPlugin.js
> + * @class
Description missing

2024-02-01 07:28 UTC, thiloSchlemmer commented on test/e2e/page.spec.js
> +			expect(await page.locator('body > *').count()).toBe(15);
a specific test for the component is missing.

```suggestion
			expect(await page.locator('ba-navigation-rail').count()).toBe(1);
```

2024-02-01 07:43 UTC, thiloSchlemmer commented on src/modules/menu/i18n/menu.provider.js
> +				menu_navigation_rail_zoom_to_extend: 'auf Bayern Zoomen',
auf Bayern (z)oomen

2024-02-01 07:49 UTC, thiloSchlemmer commented on test/service/StoreService.test.js
> +			expect(reducerKeys.length).toBe(29);
There  should be a specific test for the 'navigationRail' reducer, too.

```suggestion
			expect(reducerKeys.includes('navigationRail')).toBeTrue();
```

2024-02-01 07:55 UTC, thiloSchlemmer requested changes
Nice component!
Some minor suggestions.

2024-02-01 11:21 UTC, taulinger commented on src/modules/menu/components/navigationRail/NavigationRail.js
> + *
Have a look at our technical docs:
![grafik](https://github.com/ldbv-by/bav4/assets/49945713/8262edbf-29f1-4337-8cdc-2a8798e50b5d)

2024-02-06 10:49 UTC, thiloSchlemmer approved these changes
Thx

2024-02-12 13:16 UTC, merged